services:
  myapp:
    image: myapp:latest
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://admin:changeme@mongo:27017/shopDB?authSource=admin
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changeme





